# Generated by Django 5.0.1 on 2024-03-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        
    ]
