# Generated by Django 5.0.1 on 2024-03-24 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_event_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="dummy_field",
        ),
        migrations.AddField(
            model_name="event",
            name="User",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="image_1",
            field=models.ImageField(blank=True, null=True, upload_to="team_images/"),
        ),
        migrations.AddField(
            model_name="event",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="team_images/"),
        ),
        migrations.AddField(
            model_name="event",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to="team_images/"),
        ),
        migrations.AddField(
            model_name="event",
            name="image_4",
            field=models.ImageField(blank=True, null=True, upload_to="team_images/"),
        ),
        migrations.AddField(
            model_name="event",
            name="image_5",
            field=models.ImageField(blank=True, null=True, upload_to="team_images/"),
        ),
        migrations.AddField(
            model_name="event",
            name="team_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="team_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="team_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="team_4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="team_5",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
