# Generated by Django 5.0.1 on 2024-04-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_rename_user_event_user_remove_event_image_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("voter_hash", models.CharField(max_length=255)),
                ("previous_hash", models.CharField(max_length=255)),
            ],
        ),
    ]
